"""Add ON DELETE CASCADE to user→timesheets FK

Revision ID: 3b046da5ca3a
Revises: b35369311b7c
Create Date: 2025-07-18 09:20:41.041828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b046da5ca3a'
down_revision = 'b35369311b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timesheet', schema=None) as batch_op:
        batch_op.drop_constraint('timesheet_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False))
        batch_op.add_column(sa.Column('first_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False))

    with op.batch_alter_table('timesheet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('timesheet_ibfk_1', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
